### ISSUE TITLE
Max charge current disabling SCS

### ISSUE THREAD

**Issue by tabreu** [victronenergy/dbus-systemcalc-py#7]
When max charge current is enable on DVCC, SCS is disabled on the GX Device, even if the voltage is not being controlled by the GX Device (MPPT not in external control). 

That complain came from: https://community.victronenergy.com/questions/80143/new-vecan-mppt-charger-doesnt-use-bmv-current-valu.html?childToView=80217#comment-80217

**Comment by izak** [comment]
https://github.com/victronenergy/venus/issues/792
